#!/bin/bash

what_todo=$1
param1=$2
###################################
#require httpd.module

install()
	{
	yum -y -q install postgresql-pgpoolAdmin
	}

set()
	{
	echo "Setting /etc/httpd/conf.d/postgresql-pgpoolAdmin.conf"
		client_ip="`standmng get Client`"
		if [ "$client_ip" != "" ]
		then
			sed -i "s/<\/Location>/Allow from $client_ip\n<\/Location>/" /etc/httpd/conf.d/postgresql-pgpoolAdmin.conf
		fi

	httpd -k stop
	service httpd start
	}

unset()
	{
	echo "Setting /etc/httpd/conf.d/postgresql-pgpoolAdmin.conf"
		sed -i "/$param1/d" /etc/httpd/conf.d/postgresql-pgpoolAdmin.conf

	httpd -k stop
	service httpd start
	}

erase()
	{
	yum -y -q erase postgresql-pgpoolAdmin
	}

###################################
case $what_todo in
	install)
		echo "Installing $0..."
		install
		set
		echo
		;;
	set)
		echo "Setting $0..."
		set
		echo
		;;
	unset)
		echo "Unsetting $0..."
		if [ "$param1" = "" ]
		then
			echo -e "Error: Input parameter isn't set!\n"
			exit 1
		fi

		unset
		echo
		;;
	erase)
		echo "Erasing $0..."
		erase
		echo
		;;
	*)
		echo -e "Usage: $0 { install | set | unset <ip_addr> | erase }\n"
		exit 1
		;;
esac

