#!/bin/bash

what_todo=$1
param1=$2
###################################
#require ident.module


change_passwd()
	{
	user=$1
	pass=$2

	echo "Setting password for user: \"$user\""
	passwd $user &> /dev/null <<-EOF
		$pass
		$pass
		EOF
	}


root_pass=123456
postgres_pass=123456
user1_pass=123456
user2_pass=123456
user3_pass=123456
sepgsql_pass=123456
###################################

install()
	{
	yum -y -q install postgresql-libs postgresql postgresql-server postgresql-test postgresql-contrib
	}

init_set()
	{
	echo "run_init /etc/init.d/postgresql start" >> /etc/rc.local

	service postgresql initdb

	echo "Creating users..."
		adduser user1 
		adduser user2 
		adduser user3 
		adduser -Z dbadm_u sepgsql 
		usermod -aG wheel sepgsql 

		change_passwd user1 $user1_pass
		change_passwd user2 $user2_pass
		change_passwd user3 $user3_pass
		change_passwd sepgsql $sepgsql_pass
		change_passwd postgres $postgres_pass

	echo "Setting selinux context for users..."
		semanage user -m -r s0-s3 user_u 
		semanage login -a -s user_u -r s3 user1 
		semanage login -a -s user_u -r s2 user2 
		semanage login -a -s user_u -r s0 user3 
		semanage login -m -r s0-s3 sepgsql 
		chcon -R -l 's3' /home/user1 
		chcon -R -l 's2' /home/user2 
		chcon -R -l 's0' /home/user3 
		chcon -R -l 's0' /home/sepgsql

	iptables_mng add 5432

	echo "Setting DB for remote access /var/lib/pgsql/data/pg_hba.conf"
		echo "listen_addresses = '*'" >> /var/lib/pgsql/data/postgresql.conf

		for i in 1 2 3 4 5; do sed -i '$d' /var/lib/pgsql/data/pg_hba.conf; done

		echo "local    all             all                                       trust" >> /var/lib/pgsql/data/pg_hba.conf
		echo "# IPv4 local connections:" >> /var/lib/pgsql/data/pg_hba.conf
		echo "host    all             all             127.0.0.1/32               trust" >> /var/lib/pgsql/data/pg_hba.conf
		echo "# IPv6 local connections:" >> /var/lib/pgsql/data/pg_hba.conf
		echo "host    all             all             ::1/128                    trust" >> /var/lib/pgsql/data/pg_hba.conf
		echo -e "\n" >> /var/lib/pgsql/data/pg_hba.conf

	ips=(`standmng get allip`)
	for ((i=0; i<${#ips[@]}; i++))
		do
		netlbl add ${ips[$i]}
		echo -e "host    all             all             ${ips[$i]}/32           ident" >> /var/lib/pgsql/data/pg_hba.conf
		done

	service postgresql restart
	}

set()
	{
	echo -e "host    all             all             $param1/32           ident" >> /var/lib/pgsql/data/pg_hba.conf
	service postgresql restart
	}

unset()
	{
	sed -i "/$param1/d" /var/lib/pgsql/data/pg_hba.conf
	service postgresql restart
	}

erase()
	{
	yum -y -q erase postgresql-libs postgresql postgresql-server postgresql-test postgresql-contrib

	sed -i "/postgresql start/d" /etc/rc.local

	iptables_mng del 5432
	}

###################################
case $what_todo in
	install)
		echo "Installing $0..."
		install
		init_set
		echo
		;;
	set)
		echo "Setting $0..."
		if [ "$param1" = "" ]
		then
			echo -e "Error: Input parameter isn't set!\n"
			exit 1
		fi

		set
		echo
		;;
	unset)
		echo "Unsetting $0..."
		if [ "$param1" = "" ]
		then
			echo -e "Error: Input parameter isn't set!\n"
			exit 1
		fi

		unset
		echo
		;;
	erase)
		echo "Erasing $0..."
		erase
		echo
		;;
	*)
		echo -e "Usage: $0 { install | set <ip_addr> | unset <ip_addr> | erase }\n"
		exit 1
		;;
esac

