#!/bin/sh

if [ $# -ne 2 ]
then
    echo "Мало аргументов, переданных скрипту"
    exit 1
fi

DEST=$1
DESTDIR=$2
PGCTL=/usr/bin/pg_ctl

# Startup postgresql server
ssh -T $DEST $PGCTL -w -D $DESTDIR start 2>/dev/null 1>/dev/null < /dev/null &
