#!/bin/bash

what_todo=$1
port=$2
###################################

add()
	{
	sed -i '/REJECT/d' /etc/sysconfig/iptables
	sed -i '/COMMIT/d' /etc/sysconfig/iptables

	echo "
-A INPUT -m state --state NEW -m tcp -p tcp --dport $port -j ACCEPT
-A INPUT -p tcp -m tcp --sport 1024:65535 --dport $port -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 1024:65535 --dport $port -j ACCEPT

-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT" >> /etc/sysconfig/iptables

	service iptables restart
	}

del()
	{
	sed -i "/ $port /d" /etc/sysconfig/iptables

	service iptables restart
	}

###################################
case $what_todo in
	add)
		echo "Opening port $port..."
		if [ "$port" = "" ]
		then
			echo "Error: Input parameter isn't set!"
			exit 1
		fi
		add
		;;
	del)
		echo "Closing port $port..."
		if [ "$port" = "" ]
		then
			echo "Error: Input parameter isn't set!"
			exit 1
		fi
		del
		;;
	*)
		echo "Usage: $0 { add <port> | del <port> }"
		exit 1
		;;
esac




